# Generated by Django 2.2.26 on 2022-01-23 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateID', models.BigIntegerField()),
                ('rippleHireID', models.BigIntegerField()),
                ('candidateName', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('competency', models.TextField(blank=True, null=True)),
                ('dateAdded', models.DateField(auto_now=True, null=True)),
                ('dateUpdated', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateTimeField()),
                ('eventNotes', models.TextField()),
                ('status', models.TextField()),
                ('candidateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatehistory_candidateID', to='home.Candidates')),
            ],
        ),
    ]
